# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

levAdjacencyMatDense <- function(strings, maxdist) {
    .Call(`_RepSeqNetworkAnalysis_levAdjacencyMatDense`, strings, maxdist)
}

levAdjacencyMatSparse <- function(strings, maxdist) {
    .Call(`_RepSeqNetworkAnalysis_levAdjacencyMatSparse`, strings, maxdist)
}

levDistBounded <- function(a, b, k) {
    .Call(`_RepSeqNetworkAnalysis_levDistBounded`, a, b, k)
}

